= はじめに
:navtitle: rosa-info
include::_attributes.adoc[]

Red Hat OpenShift Service on AWS (ROSA) Lab プロジェクトは、
インストラクター主導のデモ紹介またはセルフペースの演習で、ROSAを効果的に紹介及び体感していただくことを目的としています。


[Note]
====
ROSAの概要について学習する場合、
AWSのマネージドなコンテナオーケストレーションサービスである、
Amazon ECS/EKS, ROSAの特徴の違いや想定される用途、さらにOpenShiftの標準的な仮想化機能であるOpenShift Virtualizationをご紹介している資料を参考にしてください。

この資料では、Kubernetesに興味のある人から特に聞かれることの多い、EKSとROSAについて、
いくつかのサンプルユースケースと共に、両者の違いも合わせてご紹介しています。

* https://rh-open.github.io/ocp-handson/openshift-services/_images/rosa/pdf/2025-rosa-hcp-infomation.pdf[ECS/EKS/ROSAの比較情報とROSAの紹介資料(PDFファイル)]

* https://rh-open.github.io/ocp-handson/openshift-services/_images/rosa/pdf/2025-openshift-virt-aws-public.pdf[OpenShift Virtualization on AWS with ROSA/Self-Managed OpenShift(PDFファイル)]

* https://rh-open.github.io/ocp-handson/openshift-services/_images/rosa/pdf/2023-container-openshift-information.pdf[補足情報: コンテナ/OpenShiftの紹介資料(PDFファイル)]
====


---

== 演習の前提要件

* AWSにアクセス可能なネットワーク環境
* ROSAクラスターにアクセス可能なWebブラウザ

NOTE: https://access.redhat.com/articles/4763741[「Browsers and Client Tools」表]にある、
最新版のOpenShiftに対応したWebブラウザ(Firefox/MS Edge/Chrome/Safari)のいずれかを利用します。


== 演習の進め方

* 本Labをワークショップ形式で実施する場合、[デモ]と分類している項目の内容は実施せずに、
そのまま読み進めて次の項目に進んで下さい。これらの内容は、すでに適用済みのROSAクラスターをご利用いただきます。
ROSAクラスターのアクセス情報は、インストラクターがご案内します。

* 本Labを自習形式で実施する場合、全てのコンテンツを実施してください。

[Note]
====
次のものを用意することで、このLabを自習できます。

* 有償サービスを利用可能なAWSアカウント
* 無料で作成可能な
https://cloud.redhat.com/[Red Hatアカウント] (コンソールログイン時に適宜作成して下さい)
====


== 無償で実施可能なROSA Hands On Experience (HoE)

ROSA HCP環境を利用したセルフサービスのハンズオンを、無償で実施いただくためのサービスを別途ご提供しています。
詳細については、次の資料をご参照ください。

* https://rh-open.github.io/ocp-handson/openshift-services/_images/rosa/pdf/202406-rosa-hoe.pdf[ROSAハンズオン無償体験(PDFファイル)]
* https://rheb.hatenablog.com/entry/202312-rosa-hcp-trial[Red Hat OpenShift Service on AWS (ROSA)を無料で試してみよう(ブログ)] (ROSA HCPの料金情報に関する説明も記載しています)


== 参考情報

本Labでは扱っていない情報をいくつか記載します。

AWS Security Token Service (STS)によるAmazon EFS, Amazon ECRの利用方法です。

* https://rheb.hatenablog.com/entry/202412-rosa-efs-ecr[ROSAでのAWS STSによるAmazon EFS/ECRの利用(ブログ)]

OpenShift LoggingでのLokiとAmazon CloudWatchでのロギング設定方法、実際のログ保存サイズを紹介しています。

* https://rheb.hatenablog.com/entry/202503-openshift-logging-aws[OpenShift Logging on AWSでのログサイズや利用料金を見てみる(ブログ)]

ROSA HCPクラスターではOpenShift Virtualizationによる仮想化機能が利用できます。
詳細については、次の資料をご参照ください。仮想マシン用のストレージとして、Amazon FSx for NetApp ONTAPの利用も紹介しています。

* https://rheb.hatenablog.com/entry/202410-rosa-openshift-virt[OpenShift VirtualizationをRed Hat OpenShift Service on AWS (ROSA)で試してみよう(ブログ)]
